#!/usr/bin/env bash
# Scaffold an Alembic revision and remind the author of the expand-contract and
# RLS rules. The revision is autogenerated against the current models.
#
# Usage: scripts/create_migration.sh "add cemetery parcel table"
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

MESSAGE="${1:-}"
if [ -z "$MESSAGE" ]; then
  echo "usage: scripts/create_migration.sh \"<revision message>\"" >&2
  exit 2
fi

if command -v uv >/dev/null 2>&1; then RUN="uv run"; else RUN="python"; fi

# A reachable DATABASE_URL is required for --autogenerate to compare models with
# the live schema. Fail fast rather than emit an empty/incorrect revision.
if [ -z "${DATABASE_URL:-}" ] && [ ! -f .env ]; then
  echo "error: set DATABASE_URL (or create .env) so autogenerate can compare state" >&2
  exit 1
fi

$RUN alembic revision --autogenerate -m "$MESSAGE"

cat <<'GUIDANCE'

Revision created. Before committing, confirm it follows the house rules:
  1. expand first  - additive, nullable columns / new tables; deploy; backfill.
  2. contract later - drop the old shape only in a subsequent revision.
  3. every tenant-scoped table gets a Row-Level-Security policy in the same
     revision (CREATE POLICY ... USING (tenant_id = current_setting('app.tenant_id'))).
  4. downgrade() must actually reverse upgrade() - "irreversible" is a bug.
GUIDANCE
