#!/usr/bin/env python3
"""Export the live OpenAPI document for the ``/v1`` contract.

The application is the single source of truth: this script imports it, calls
``app.openapi()`` and writes a deterministic (key-sorted, two-space indented)
JSON snapshot. CI diffs the committed ``docs/api/v1-openapi.json`` against a
fresh export so the published contract can never silently drift from the code
(ADR-006, ``docs/api/versioning-policy.md``).

Usage::

    python scripts/export_openapi.py                     # write docs/api/v1-openapi.json
    python scripts/export_openapi.py --out /tmp/x.json   # write elsewhere
    python scripts/export_openapi.py --check             # fail if the snapshot is stale
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any

# ``Settings`` requires DATABASE_URL at import time. Provide a placeholder when
# the caller has not: exporting the schema opens no connection, so the value is
# irrelevant here and never reaches a network.
os.environ.setdefault("DATABASE_URL", "postgresql+psycopg://export:export@localhost:5432/export")

DEFAULT_OUT = Path("docs/api/v1-openapi.json")


def _render(spec: dict[str, Any]) -> str:
    """Serialise deterministically so a diff shows only real contract changes."""
    return json.dumps(spec, sort_keys=True, indent=2, ensure_ascii=False) + "\n"


def build_spec() -> dict[str, Any]:
    """Return the OpenAPI document generated by the running application."""
    # Imported late, after the environment placeholder above is in place.
    from app.main import app

    return app.openapi()


def main(argv: list[str] | None = None) -> int:
    """Entry point; returns a process exit code."""
    parser = argparse.ArgumentParser(description="Export the /v1 OpenAPI snapshot.")
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUT,
        help=f"destination file (default: {DEFAULT_OUT})",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the destination differs from a fresh export; never writes",
    )
    args = parser.parse_args(argv)

    rendered = _render(build_spec())

    if args.check:
        current = args.out.read_text(encoding="utf-8") if args.out.exists() else ""
        if current != rendered:
            print(
                f"{args.out} is stale; re-run scripts/export_openapi.py and commit",
                file=sys.stderr,
            )
            return 1
        print(f"{args.out} is up to date")
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(rendered, encoding="utf-8")
    print(f"wrote {args.out} ({len(rendered)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
